using System;

namespace THNETII.WinApi.Native.WinBase
{
    [Flags]
    public enum FORMAT_MESSAGE_FLAGS : int
    {
        FORMAT_MESSAGE_ALLOCATE_BUFFER = WinBaseConstants.FORMAT_MESSAGE_ALLOCATE_BUFFER,
        FORMAT_MESSAGE_IGNORE_INSERTS = WinBaseConstants.FORMAT_MESSAGE_IGNORE_INSERTS,
        FORMAT_MESSAGE_FROM_STRING = WinBaseConstants.FORMAT_MESSAGE_FROM_STRING,
        FORMAT_MESSAGE_FROM_HMODULE = WinBaseConstants.FORMAT_MESSAGE_FROM_HMODULE,
        FORMAT_MESSAGE_FROM_SYSTEM = WinBaseConstants.FORMAT_MESSAGE_FROM_SYSTEM,
        FORMAT_MESSAGE_ARGUMENT_ARRAY = WinBaseConstants.FORMAT_MESSAGE_ARGUMENT_ARRAY,
    }
}
