using System;

namespace THNETII.WinApi.Native.WinNT
{
    [Flags]
    public enum CONTEXT_FLAGS : int
    {
        CONTEXT_AMD64 = WinNTConstants.CONTEXT_AMD64,
        CONTEXT_ARM = WinNTConstants.CONTEXT_ARM,
        CONTEXT_ARM64 = WinNTConstants.CONTEXT_ARM64,
        CONTEXT_i386 = WinNTConstants.CONTEXT_i386,
        CONTEXT_i486 = WinNTConstants.CONTEXT_i486,

        CONTEXT_CONTROL = WinNTConstants.CONTEXT_CONTROL,
        CONTEXT_INTEGER = WinNTConstants.CONTEXT_INTEGER,
        CONTEXT_SEGMENTS = WinNTConstants.CONTEXT_SEGMENTS,
        CONTEXT_FLOATING_POINT = WinNTConstants.CONTEXT_FLOATING_POINT,
        CONTEXT_DEBUG_REGISTERS = WinNTConstants.CONTEXT_DEBUG_REGISTERS,
        CONTEXT_EXTENDED_REGISTERS = WinNTConstants.CONTEXT_EXTENDED_REGISTERS,

        CONTEXT_ARM64_CONTROL = WinNTConstants.CONTEXT_ARM64_CONTROL,
        CONTEXT_ARM64_INTEGER = WinNTConstants.CONTEXT_ARM64_INTEGER,
        CONTEXT_ARM64_FLOATING_POINT = WinNTConstants.CONTEXT_ARM64_FLOATING_POINT,
        CONTEXT_ARM64_DEBUG_REGISTERS = WinNTConstants.CONTEXT_ARM64_DEBUG_REGISTERS,
        CONTEXT_ARM64_X18 = WinNTConstants.CONTEXT_ARM64_X18,

        CONTEXT_ARM64_FULL = WinNTConstants.CONTEXT_ARM64_FULL,
        CONTEXT_ARM64_ALL = WinNTConstants.CONTEXT_ARM64_ALL,

        CONTEXT_FULL = WinNTConstants.CONTEXT_FULL,

        CONTEXT_ALL = WinNTConstants.CONTEXT_ALL,

        CONTEXT_XSTATE = WinNTConstants.CONTEXT_XSTATE,

        CONTEXT_KERNEL_DEBUGGER = WinNTConstants.CONTEXT_KERNEL_DEBUGGER,

        CONTEXT_EXCEPTION_ACTIVE = WinNTConstants.CONTEXT_EXCEPTION_ACTIVE,
        CONTEXT_SERVICE_ACTIVE = WinNTConstants.CONTEXT_SERVICE_ACTIVE,
        CONTEXT_EXCEPTION_REQUEST = WinNTConstants.CONTEXT_EXCEPTION_REQUEST,
        CONTEXT_EXCEPTION_REPORTING = WinNTConstants.CONTEXT_EXCEPTION_REPORTING,

        CONTEXT_UNWOUND_TO_CALL = WinNTConstants.CONTEXT_UNWOUND_TO_CALL,
        CONTEXT_RET_TO_GUEST = WinNTConstants.CONTEXT_RET_TO_GUEST,

        WOW64_CONTEXT_i386 = WinNTConstants.WOW64_CONTEXT_i386,
        WOW64_CONTEXT_i486 = WinNTConstants.WOW64_CONTEXT_i486,

        WOW64_CONTEXT_CONTROL = WinNTConstants.WOW64_CONTEXT_CONTROL,
        WOW64_CONTEXT_INTEGER = WinNTConstants.WOW64_CONTEXT_INTEGER,
        WOW64_CONTEXT_SEGMENTS = WinNTConstants.WOW64_CONTEXT_SEGMENTS,
        WOW64_CONTEXT_FLOATING_POINT = WinNTConstants.WOW64_CONTEXT_FLOATING_POINT,
        WOW64_CONTEXT_DEBUG_REGISTERS = WinNTConstants.WOW64_CONTEXT_DEBUG_REGISTERS,
        WOW64_CONTEXT_EXTENDED_REGISTERS = WinNTConstants.WOW64_CONTEXT_EXTENDED_REGISTERS,

        WOW64_CONTEXT_FULL = WinNTConstants.WOW64_CONTEXT_FULL,

        WOW64_CONTEXT_ALL = WinNTConstants.WOW64_CONTEXT_ALL,

        WOW64_CONTEXT_XSTATE = WinNTConstants.WOW64_CONTEXT_XSTATE,

        WOW64_CONTEXT_EXCEPTION_ACTIVE = WinNTConstants.WOW64_CONTEXT_EXCEPTION_ACTIVE,
        WOW64_CONTEXT_SERVICE_ACTIVE = WinNTConstants.WOW64_CONTEXT_SERVICE_ACTIVE,
        WOW64_CONTEXT_EXCEPTION_REQUEST = WinNTConstants.WOW64_CONTEXT_EXCEPTION_REQUEST,
        WOW64_CONTEXT_EXCEPTION_REPORTING = WinNTConstants.WOW64_CONTEXT_EXCEPTION_REPORTING,
    }
}
