using System.Diagnostics.CodeAnalysis;

namespace THNETII.WinApi.Native.WinNT
{
    /// <summary>
    /// Storage classes.
    /// </summary>
    [SuppressMessage("Design", "CA1028: Enum Storage should be Int32")]
    public enum IMAGE_SYM_CLASS : byte
    {
        IMAGE_SYM_CLASS_END_OF_FUNCTION = WinNTConstants.IMAGE_SYM_CLASS_END_OF_FUNCTION,
        IMAGE_SYM_CLASS_NULL = WinNTConstants.IMAGE_SYM_CLASS_NULL,
        IMAGE_SYM_CLASS_AUTOMATIC = WinNTConstants.IMAGE_SYM_CLASS_AUTOMATIC,
        IMAGE_SYM_CLASS_EXTERNAL = WinNTConstants.IMAGE_SYM_CLASS_EXTERNAL,
        IMAGE_SYM_CLASS_STATIC = WinNTConstants.IMAGE_SYM_CLASS_STATIC,
        IMAGE_SYM_CLASS_REGISTER = WinNTConstants.IMAGE_SYM_CLASS_REGISTER,
        IMAGE_SYM_CLASS_EXTERNAL_DEF = WinNTConstants.IMAGE_SYM_CLASS_EXTERNAL_DEF,
        IMAGE_SYM_CLASS_LABEL = WinNTConstants.IMAGE_SYM_CLASS_LABEL,
        IMAGE_SYM_CLASS_UNDEFINED_LABEL = WinNTConstants.IMAGE_SYM_CLASS_UNDEFINED_LABEL,
        IMAGE_SYM_CLASS_MEMBER_OF_STRUCT = WinNTConstants.IMAGE_SYM_CLASS_MEMBER_OF_STRUCT,
        IMAGE_SYM_CLASS_ARGUMENT = WinNTConstants.IMAGE_SYM_CLASS_ARGUMENT,
        IMAGE_SYM_CLASS_STRUCT_TAG = WinNTConstants.IMAGE_SYM_CLASS_STRUCT_TAG,
        IMAGE_SYM_CLASS_MEMBER_OF_UNION = WinNTConstants.IMAGE_SYM_CLASS_MEMBER_OF_UNION,
        IMAGE_SYM_CLASS_UNION_TAG = WinNTConstants.IMAGE_SYM_CLASS_UNION_TAG,
        IMAGE_SYM_CLASS_TYPE_DEFINITION = WinNTConstants.IMAGE_SYM_CLASS_TYPE_DEFINITION,
        IMAGE_SYM_CLASS_UNDEFINED_STATIC = WinNTConstants.IMAGE_SYM_CLASS_UNDEFINED_STATIC,
        IMAGE_SYM_CLASS_ENUM_TAG = WinNTConstants.IMAGE_SYM_CLASS_ENUM_TAG,
        IMAGE_SYM_CLASS_MEMBER_OF_ENUM = WinNTConstants.IMAGE_SYM_CLASS_MEMBER_OF_ENUM,
        IMAGE_SYM_CLASS_REGISTER_PARAM = WinNTConstants.IMAGE_SYM_CLASS_REGISTER_PARAM,
        IMAGE_SYM_CLASS_BIT_FIELD = WinNTConstants.IMAGE_SYM_CLASS_BIT_FIELD,

        IMAGE_SYM_CLASS_FAR_EXTERNAL = WinNTConstants.IMAGE_SYM_CLASS_FAR_EXTERNAL,

        IMAGE_SYM_CLASS_BLOCK = WinNTConstants.IMAGE_SYM_CLASS_BLOCK,
        IMAGE_SYM_CLASS_FUNCTION = WinNTConstants.IMAGE_SYM_CLASS_FUNCTION,
        IMAGE_SYM_CLASS_END_OF_STRUCT = WinNTConstants.IMAGE_SYM_CLASS_END_OF_STRUCT,
        IMAGE_SYM_CLASS_FILE = WinNTConstants.IMAGE_SYM_CLASS_FILE,
        // new
        IMAGE_SYM_CLASS_SECTION = WinNTConstants.IMAGE_SYM_CLASS_SECTION,
        IMAGE_SYM_CLASS_WEAK_EXTERNAL = WinNTConstants.IMAGE_SYM_CLASS_WEAK_EXTERNAL,

        IMAGE_SYM_CLASS_CLR_TOKEN = WinNTConstants.IMAGE_SYM_CLASS_CLR_TOKEN,
    }
}
