namespace THNETII.WinApi.Native.WinNT
{
    /// <summary>
    /// Completion Port Messages for job objects
    /// </summary>
    public enum JOB_OBJECT_MSG_TYPE
    {
        JOB_OBJECT_MSG_END_OF_JOB_TIME = WinNTConstants.JOB_OBJECT_MSG_END_OF_JOB_TIME,
        JOB_OBJECT_MSG_END_OF_PROCESS_TIME = WinNTConstants.JOB_OBJECT_MSG_END_OF_PROCESS_TIME,
        JOB_OBJECT_MSG_ACTIVE_PROCESS_LIMIT = WinNTConstants.JOB_OBJECT_MSG_ACTIVE_PROCESS_LIMIT,
        JOB_OBJECT_MSG_ACTIVE_PROCESS_ZERO = WinNTConstants.JOB_OBJECT_MSG_ACTIVE_PROCESS_ZERO,
        JOB_OBJECT_MSG_NEW_PROCESS = WinNTConstants.JOB_OBJECT_MSG_NEW_PROCESS,
        JOB_OBJECT_MSG_EXIT_PROCESS = WinNTConstants.JOB_OBJECT_MSG_EXIT_PROCESS,
        JOB_OBJECT_MSG_ABNORMAL_EXIT_PROCESS = WinNTConstants.JOB_OBJECT_MSG_ABNORMAL_EXIT_PROCESS,
        JOB_OBJECT_MSG_PROCESS_MEMORY_LIMIT = WinNTConstants.JOB_OBJECT_MSG_PROCESS_MEMORY_LIMIT,
        JOB_OBJECT_MSG_JOB_MEMORY_LIMIT = WinNTConstants.JOB_OBJECT_MSG_JOB_MEMORY_LIMIT,
        JOB_OBJECT_MSG_NOTIFICATION_LIMIT = WinNTConstants.JOB_OBJECT_MSG_NOTIFICATION_LIMIT,
        JOB_OBJECT_MSG_JOB_CYCLE_TIME_LIMIT = WinNTConstants.JOB_OBJECT_MSG_JOB_CYCLE_TIME_LIMIT,
        JOB_OBJECT_MSG_SILO_TERMINATED = WinNTConstants.JOB_OBJECT_MSG_SILO_TERMINATED,
    }
}
