using System.Runtime.InteropServices;

namespace THNETII.WinApi.Native.WinNT
{
    // C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\winnt.h, line 11907
    /// <summary>
    /// Contains information used to control the network traffic for a job. This structure is used by the
    /// <see cref="SetInformationJobObject"/> and <see cref="QueryInformationJobObject"/> functions with the
    /// <see cref="JobObjectNetRateControlInformation"/> information class.
    /// </summary>
    /// <remarks>
    /// You can only set the control of the network traffic on one job in a hierarchy of nested jobs. The
    /// settings that you specify apply to that job and the child jobs in the hierarchy for that job. The
    /// settings do not apply to the chain of jobs from the parent job up to the top of the hierarchy. You
    /// can change the settings on the original job in the hierarchy on which you set rate control.
    /// However, attempts to set values for the control of the network rate for any other jobs in the
    /// hierarchy, including the parent jobs, fail.
    /// <para>Microsoft Docs page: <a href="https://docs.microsoft.com/en-us/windows/desktop/api/winnt/ns-winnt-jobobject_net_rate_control_information">JOBOBJECT_NET_RATE_CONTROL_INFORMATION structure</a></para>
    /// </remarks>
    /// <seealso cref="JOB_OBJECT_NET_RATE_CONTROL_FLAGS"/>
    /// <seealso cref="QueryInformationJobObject"/>
    /// <seealso cref="SetInformationJobObject"/>
    [StructLayout(LayoutKind.Sequential)]
    public struct JOBOBJECT_NET_RATE_CONTROL_INFORMATION
    {
        /// <summary>
        /// The maximum bandwidth for outgoing network traffic for the job, in bytes.
        /// </summary>
        public long MaxBandwidth;
        /// <summary>
        /// A combination of <see cref="JOB_OBJECT_NET_RATE_CONTROL_FLAGS"/> enumeration values that specify the
        /// scheduling policy for network rate control.
        /// </summary>
        public JOB_OBJECT_NET_RATE_CONTROL_FLAGS ControlFlags;
        /// <summary>
        /// The value to use for the Differentiated Service code point (DSCP) field to turn on network quality
        /// of service (QoS) for all outgoing network traffic generated by the processes of the job object. The
        /// valid range is from <c>0x00</c> through <c>0x3F</c>. For information about DSCP, see <a href="https://msdn.microsoft.com/0b4afa74-0198-482d-af72-9ddf135a8e2f">Differentiated Services</a>.
        /// </summary>
        public byte DscpTag;
    }
}
