using System;

namespace THNETII.WinApi.Native.WinNT
{
    [Flags]
    public enum CONTEXT_FLAGS : int
    {
        CONTEXT_i386 = WinNTConstants.CONTEXT_i386,
        CONTEXT_i486 = WinNTConstants.CONTEXT_i486,

        CONTEXT_CONTROL = WinNTConstants.CONTEXT_CONTROL,
        CONTEXT_INTEGER = WinNTConstants.CONTEXT_INTEGER,
        CONTEXT_SEGMENTS = WinNTConstants.CONTEXT_SEGMENTS,
        CONTEXT_FLOATING_POINT = WinNTConstants.CONTEXT_FLOATING_POINT,
        CONTEXT_DEBUG_REGISTERS = WinNTConstants.CONTEXT_DEBUG_REGISTERS,
        CONTEXT_EXTENDED_REGISTERS = WinNTConstants.CONTEXT_EXTENDED_REGISTERS,

        CONTEXT_FULL = WinNTConstants.CONTEXT_FULL,

        CONTEXT_ALL = WinNTConstants.CONTEXT_ALL,

        CONTEXT_XSTATE = WinNTConstants.CONTEXT_XSTATE,

        CONTEXT_EXCEPTION_ACTIVE = WinNTConstants.CONTEXT_EXCEPTION_ACTIVE,
        CONTEXT_SERVICE_ACTIVE = WinNTConstants.CONTEXT_SERVICE_ACTIVE,
        CONTEXT_EXCEPTION_REQUEST = WinNTConstants.CONTEXT_EXCEPTION_REQUEST,
        CONTEXT_EXCEPTION_REPORTING = WinNTConstants.CONTEXT_EXCEPTION_REPORTING,
    }
}
