using System;

namespace THNETII.WinApi.Native.WinNT
{
    // C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\winnt.h, line 15155
    [Flags]
    public enum DIAGNOSTIC_REASON_FLAGS : int
    {
        DIAGNOSTIC_REASON_SIMPLE_STRING = WinNTConstants.DIAGNOSTIC_REASON_SIMPLE_STRING,
        DIAGNOSTIC_REASON_DETAILED_STRING = WinNTConstants.DIAGNOSTIC_REASON_DETAILED_STRING,
        DIAGNOSTIC_REASON_NOT_SPECIFIED = WinNTConstants.DIAGNOSTIC_REASON_NOT_SPECIFIED,
        DIAGNOSTIC_REASON_INVALID_FLAGS = WinNTConstants.DIAGNOSTIC_REASON_INVALID_FLAGS,
    }
}
