using System;
using System.Collections.Generic;
using System.Text;

namespace THNETII.WinApi.Native.WinNT
{
    /// <summary>
    /// Based relocation types.
    /// </summary>
    public enum IMAGE_REL_BASED_TYPE
    {
        IMAGE_REL_BASED_ABSOLUTE = WinNTConstants.IMAGE_REL_BASED_ABSOLUTE,
        IMAGE_REL_BASED_HIGH = WinNTConstants.IMAGE_REL_BASED_HIGH,
        IMAGE_REL_BASED_LOW = WinNTConstants.IMAGE_REL_BASED_LOW,
        IMAGE_REL_BASED_HIGHLOW = WinNTConstants.IMAGE_REL_BASED_HIGHLOW,
        IMAGE_REL_BASED_HIGHADJ = WinNTConstants.IMAGE_REL_BASED_HIGHADJ,
        IMAGE_REL_BASED_MACHINE_SPECIFIC_5 = WinNTConstants.IMAGE_REL_BASED_MACHINE_SPECIFIC_5,
        IMAGE_REL_BASED_RESERVED = WinNTConstants.IMAGE_REL_BASED_RESERVED,
        IMAGE_REL_BASED_MACHINE_SPECIFIC_7 = WinNTConstants.IMAGE_REL_BASED_MACHINE_SPECIFIC_7,
        IMAGE_REL_BASED_MACHINE_SPECIFIC_8 = WinNTConstants.IMAGE_REL_BASED_MACHINE_SPECIFIC_8,
        IMAGE_REL_BASED_MACHINE_SPECIFIC_9 = WinNTConstants.IMAGE_REL_BASED_MACHINE_SPECIFIC_9,
        IMAGE_REL_BASED_DIR64 = WinNTConstants.IMAGE_REL_BASED_DIR64,

        //
        // Platform-specific based relocation types.
        //

        IMAGE_REL_BASED_IA64_IMM64 = WinNTConstants.IMAGE_REL_BASED_IA64_IMM64,

        IMAGE_REL_BASED_MIPS_JMPADDR = WinNTConstants.IMAGE_REL_BASED_MIPS_JMPADDR,
        IMAGE_REL_BASED_MIPS_JMPADDR16 = WinNTConstants.IMAGE_REL_BASED_MIPS_JMPADDR16,

        IMAGE_REL_BASED_ARM_MOV32 = WinNTConstants.IMAGE_REL_BASED_ARM_MOV32,
        IMAGE_REL_BASED_THUMB_MOV32 = WinNTConstants.IMAGE_REL_BASED_THUMB_MOV32,
    }
}
