namespace THNETII.WinApi.Native.WinNT
{
    public enum PROCESSOR_ARCHITECTURE
    {
        PROCESSOR_ARCHITECTURE_INTEL = WinNTConstants.PROCESSOR_ARCHITECTURE_INTEL,
        PROCESSOR_ARCHITECTURE_MIPS = WinNTConstants.PROCESSOR_ARCHITECTURE_MIPS,
        PROCESSOR_ARCHITECTURE_ALPHA = WinNTConstants.PROCESSOR_ARCHITECTURE_ALPHA,
        PROCESSOR_ARCHITECTURE_PPC = WinNTConstants.PROCESSOR_ARCHITECTURE_PPC,
        PROCESSOR_ARCHITECTURE_SHX = WinNTConstants.PROCESSOR_ARCHITECTURE_SHX,
        PROCESSOR_ARCHITECTURE_ARM = WinNTConstants.PROCESSOR_ARCHITECTURE_ARM,
        PROCESSOR_ARCHITECTURE_IA64 = WinNTConstants.PROCESSOR_ARCHITECTURE_IA64,
        PROCESSOR_ARCHITECTURE_ALPHA64 = WinNTConstants.PROCESSOR_ARCHITECTURE_ALPHA64,
        PROCESSOR_ARCHITECTURE_MSIL = WinNTConstants.PROCESSOR_ARCHITECTURE_MSIL,
        PROCESSOR_ARCHITECTURE_AMD64 = WinNTConstants.PROCESSOR_ARCHITECTURE_AMD64,
        PROCESSOR_ARCHITECTURE_IA32_ON_WIN64 = WinNTConstants.PROCESSOR_ARCHITECTURE_IA32_ON_WIN64,
        PROCESSOR_ARCHITECTURE_NEUTRAL = WinNTConstants.PROCESSOR_ARCHITECTURE_NEUTRAL,
        PROCESSOR_ARCHITECTURE_ARM64 = WinNTConstants.PROCESSOR_ARCHITECTURE_ARM64,
        PROCESSOR_ARCHITECTURE_ARM32_ON_WIN64 = WinNTConstants.PROCESSOR_ARCHITECTURE_ARM32_ON_WIN64,
        PROCESSOR_ARCHITECTURE_IA32_ON_ARM64 = WinNTConstants.PROCESSOR_ARCHITECTURE_IA32_ON_ARM64,

        PROCESSOR_ARCHITECTURE_UNKNOWN = WinNTConstants.PROCESSOR_ARCHITECTURE_UNKNOWN,
    }
}
