using System;

namespace THNETII.WinApi.WinNT
{
    [Flags]
    public enum VER_FLAGS : int
    {
        VER_SERVER_NT = WinNTConstants.VER_SERVER_NT,
        VER_WORKSTATION_NT = WinNTConstants.VER_WORKSTATION_NT,
        VER_SUITE_SMALLBUSINESS = WinNTConstants.VER_SUITE_SMALLBUSINESS,
        VER_SUITE_ENTERPRISE = WinNTConstants.VER_SUITE_ENTERPRISE,
        VER_SUITE_BACKOFFICE = WinNTConstants.VER_SUITE_BACKOFFICE,
        VER_SUITE_COMMUNICATIONS = WinNTConstants.VER_SUITE_COMMUNICATIONS,
        VER_SUITE_TERMINAL = WinNTConstants.VER_SUITE_TERMINAL,
        VER_SUITE_SMALLBUSINESS_RESTRICTED = WinNTConstants.VER_SUITE_SMALLBUSINESS_RESTRICTED,
        VER_SUITE_EMBEDDEDNT = WinNTConstants.VER_SUITE_EMBEDDEDNT,
        VER_SUITE_DATACENTER = WinNTConstants.VER_SUITE_DATACENTER,
        VER_SUITE_SINGLEUSERTS = WinNTConstants.VER_SUITE_SINGLEUSERTS,
        VER_SUITE_PERSONAL = WinNTConstants.VER_SUITE_PERSONAL,
        VER_SUITE_BLADE = WinNTConstants.VER_SUITE_BLADE,
        VER_SUITE_EMBEDDED_RESTRICTED = WinNTConstants.VER_SUITE_EMBEDDED_RESTRICTED,
        VER_SUITE_SECURITY_APPLIANCE = WinNTConstants.VER_SUITE_SECURITY_APPLIANCE,
        VER_SUITE_STORAGE_SERVER = WinNTConstants.VER_SUITE_STORAGE_SERVER,
        VER_SUITE_COMPUTE_SERVER = WinNTConstants.VER_SUITE_COMPUTE_SERVER,
        VER_SUITE_WH_SERVER = WinNTConstants.VER_SUITE_WH_SERVER,
        VER_SUITE_MULTIUSERTS = WinNTConstants.VER_SUITE_MULTIUSERTS,
    }
}
