using System;

namespace THNETII.WinApi.Native.Sspi
{
    [Flags]
    public enum ISC_RET_FLAGS : int
    {
        ISC_RET_DELEGATE = SspiConstants.ISC_RET_DELEGATE,
        ISC_RET_MUTUAL_AUTH = SspiConstants.ISC_RET_MUTUAL_AUTH,
        ISC_RET_REPLAY_DETECT = SspiConstants.ISC_RET_REPLAY_DETECT,
        ISC_RET_SEQUENCE_DETECT = SspiConstants.ISC_RET_SEQUENCE_DETECT,
        ISC_RET_CONFIDENTIALITY = SspiConstants.ISC_RET_CONFIDENTIALITY,
        ISC_RET_USE_SESSION_KEY = SspiConstants.ISC_RET_USE_SESSION_KEY,
        ISC_RET_USED_COLLECTED_CREDS = SspiConstants.ISC_RET_USED_COLLECTED_CREDS,
        ISC_RET_USED_SUPPLIED_CREDS = SspiConstants.ISC_RET_USED_SUPPLIED_CREDS,
        ISC_RET_ALLOCATED_MEMORY = SspiConstants.ISC_RET_ALLOCATED_MEMORY,
        ISC_RET_USED_DCE_STYLE = SspiConstants.ISC_RET_USED_DCE_STYLE,
        ISC_RET_DATAGRAM = SspiConstants.ISC_RET_DATAGRAM,
        ISC_RET_CONNECTION = SspiConstants.ISC_RET_CONNECTION,
        ISC_RET_INTERMEDIATE_RETURN = SspiConstants.ISC_RET_INTERMEDIATE_RETURN,
        ISC_RET_CALL_LEVEL = SspiConstants.ISC_RET_CALL_LEVEL,
        ISC_RET_EXTENDED_ERROR = SspiConstants.ISC_RET_EXTENDED_ERROR,
        ISC_RET_STREAM = SspiConstants.ISC_RET_STREAM,
        ISC_RET_INTEGRITY = SspiConstants.ISC_RET_INTEGRITY,
        ISC_RET_IDENTIFY = SspiConstants.ISC_RET_IDENTIFY,
        ISC_RET_NULL_SESSION = SspiConstants.ISC_RET_NULL_SESSION,
        ISC_RET_MANUAL_CRED_VALIDATION = SspiConstants.ISC_RET_MANUAL_CRED_VALIDATION,
        ISC_RET_RESERVED1 = SspiConstants.ISC_RET_RESERVED1,
        ISC_RET_FRAGMENT_ONLY = SspiConstants.ISC_RET_FRAGMENT_ONLY,
        // This exists only in Windows Vista and greater
        ISC_RET_FORWARD_CREDENTIALS = SspiConstants.ISC_RET_FORWARD_CREDENTIALS,

        ISC_RET_USED_HTTP_STYLE = SspiConstants.ISC_RET_USED_HTTP_STYLE,
        ISC_RET_NO_ADDITIONAL_TOKEN = SspiConstants.ISC_RET_NO_ADDITIONAL_TOKEN, // *INTERNAL*
        ISC_RET_REAUTHENTICATION = SspiConstants.ISC_RET_REAUTHENTICATION, // *INTERNAL*
        ISC_RET_CONFIDENTIALITY_ONLY = SspiConstants.ISC_RET_CONFIDENTIALITY_ONLY, // honored by SPNEGO/Kerberos
    }
}
