using System;

namespace THNETII.WinApi.Native.Sspi
{

    [Flags]
    public enum SECPKG_CALLFLAGS : int
    {
        SECPKG_CALLFLAGS_APPCONTAINER = SspiConstants.SECPKG_CALLFLAGS_APPCONTAINER,
        SECPKG_CALLFLAGS_APPCONTAINER_AUTHCAPABLE = SspiConstants.SECPKG_CALLFLAGS_APPCONTAINER_AUTHCAPABLE,
        SECPKG_CALLFLAGS_FORCE_SUPPLIED = SspiConstants.SECPKG_CALLFLAGS_FORCE_SUPPLIED,
        SECPKG_CALLFLAGS_APPCONTAINER_UPNCAPABLE = SspiConstants.SECPKG_CALLFLAGS_APPCONTAINER_UPNCAPABLE,
    }
}
