namespace THNETII.WinApi.Native.AuthZ
{
    public enum AUTHZ_SECURITY_ATTRIBUTE_TYPE
    {
        AUTHZ_SECURITY_ATTRIBUTE_TYPE_INVALID = AuthZConstants.AUTHZ_SECURITY_ATTRIBUTE_TYPE_INVALID,

        AUTHZ_SECURITY_ATTRIBUTE_TYPE_INT64 = AuthZConstants.AUTHZ_SECURITY_ATTRIBUTE_TYPE_INT64,
        AUTHZ_SECURITY_ATTRIBUTE_TYPE_UINT64 = AuthZConstants.AUTHZ_SECURITY_ATTRIBUTE_TYPE_UINT64,
        AUTHZ_SECURITY_ATTRIBUTE_TYPE_STRING = AuthZConstants.AUTHZ_SECURITY_ATTRIBUTE_TYPE_STRING,
        AUTHZ_SECURITY_ATTRIBUTE_TYPE_FQBN = AuthZConstants.AUTHZ_SECURITY_ATTRIBUTE_TYPE_FQBN,
        AUTHZ_SECURITY_ATTRIBUTE_TYPE_SID = AuthZConstants.AUTHZ_SECURITY_ATTRIBUTE_TYPE_SID,
        AUTHZ_SECURITY_ATTRIBUTE_TYPE_BOOLEAN = AuthZConstants.AUTHZ_SECURITY_ATTRIBUTE_TYPE_BOOLEAN,
        AUTHZ_SECURITY_ATTRIBUTE_TYPE_OCTET_STRING = AuthZConstants.AUTHZ_SECURITY_ATTRIBUTE_TYPE_OCTET_STRING,
    }
}
